name: Android CI

on:
  push:
  pull_request:
    types:
      - opened
      - reopened

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Setup JDK 17 using the temurin distribution
    - uses: actions/checkout@v3
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    # Copy the Google Service file to the app directory, decode it from base64 and save it as google-services.json
    - name: Load Google Service file
      env:
        DATA: ${{ secrets.GOOGLE_SERVICES_JSON }}
      run: echo $DATA | base64 -di > app/google-services.json

    # Grant execute permission to gradlew
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    # Build the project using Gradle
    - name: Build with Gradle
      run: ./gradlew build

    # Run the tests
    - name: Run tests
      run: ./gradlew test
